package com.hibernate.pojo;

/**
 * User generated by MyEclipse Persistence Tools
 */

public class User implements java.io.Serializable {

	// Fields

	private Integer uid;

	private String upwd;

	private String uinfor;

	private String uname;

	// Constructors

	/** default constructor */
	public User() {
	}

	public User(String upwd, String uname) {
		super();
		this.upwd = upwd;
		this.uname = uname;
	}

	/** full constructor */
	public User(String upwd, String uinfor, String uname) {
		this.upwd = upwd;
		this.uinfor = uinfor;
		this.uname = uname;
	}

	// Property accessors

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUpwd() {
		return this.upwd;
	}

	public void setUpwd(String upwd) {
		this.upwd = upwd;
	}

	public String getUinfor() {
		return this.uinfor;
	}

	public void setUinfor(String uinfor) {
		this.uinfor = uinfor;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

}