/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.struts.form.LoginStruts1Form;
import com.spring.delegate.*;
import com.hibernate.pojo.*;

/**
 * Struts1自己管理自己的Action，只利用了Spring的IOC和AOP，
 * 以ApplicationContext的封装类和方法Getbean（）
 * 来访问业务代理对象Delegate
 * @author Administrator
 *
 */
public class LoginStruts1Action extends BaseAction {

	private UserDelegate ud;

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try {
			LoginStruts1Form loginForm = (LoginStruts1Form) form;
			User u = new User(loginForm.getUpwd(), loginForm.getUname());
			ud = (UserDelegate) this.getApplicationContext().getBean(
					"userDelegate"); // 此处的bean name 不能是其代理name : userDelegateProxy
			boolean falt = ud.validate(u);
			if ( falt == true) {
				request.getSession().setAttribute("loginUser", u);
				return mapping.findForward("success");
			} else {
				loginForm.setUname("");
				loginForm.setUpwd("");
				return mapping.findForward("faile");
			}
		} catch (Exception ex) {
			ex.printStackTrace();
			return mapping.findForward("error");
		}
	}
}