/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.hibernate.pojo.User;
import com.spring.delegate.UserDelegate;
import com.struts.form.LoginStruts1Form;

/**
 * Spring直接管理Struts1以及它的Action 当Action需要访问业务代理对象Delegate时，
 * 直接通过Set注入，从Spring文件中直接获取 其更能体现出SHS这三个框架紧耦合在一起的作用
 * 
 * @author Administrator
 * 
 */

public class SpringStruts1ActionAction extends Action {

	private UserDelegate ud;

	public UserDelegate getUd() {
		return ud;
	}

	public void setUd(UserDelegate ud) {
		this.ud = ud;
	}

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		try {
			LoginStruts1Form loginForm = (LoginStruts1Form) form;
			User u = new User(loginForm.getUpwd(), loginForm.getUname());
			boolean falt = ud.validate(u);
			if (falt == true) {
				request.getSession().setAttribute("loginUser", u);
				return mapping.findForward("success");
			} else {
				loginForm.setUname("");
				loginForm.setUpwd("");
				return mapping.findForward("faile");
			}
		} catch (Exception ex) {
			ex.printStackTrace();
			return mapping.findForward("error");
		}
	}
}